# Generated by Django 6.0.4 on 2026-04-13 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва атрибута')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='URL-ідентифікатор')),
                ('type', models.CharField(choices=[('text', 'Текст'), ('number', 'Число'), ('boolean', 'Так/Ні'), ('color', 'Колір'), ('date', 'Дата')], default='text', max_length=20, verbose_name='Тип даних')),
                ('unit', models.CharField(blank=True, help_text='наприклад: GB, GHz, см, років', max_length=20, verbose_name='Одиниця виміру')),
                ('is_filterable', models.BooleanField(default=True, verbose_name='Використовувати у фільтрах')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Показувати на картці товару')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок сортування')),
            ],
            options={
                'verbose_name': 'Атрибут',
                'verbose_name_plural': 'Атрибути',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True, verbose_name='Ключ сесії')),
                ('items', models.JSONField(default=list, verbose_name='Товари в кошику')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Кошик',
                'verbose_name_plural': 'Кошики',
            },
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.CharField(blank=True, max_length=255, verbose_name='Значення (текст)')),
                ('value_number', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Значення (число)')),
                ('value_boolean', models.BooleanField(default=False, verbose_name='Значення (так/ні)')),
                ('value_color', models.CharField(blank=True, help_text='HEX код, наприклад #FF0000', max_length=7, verbose_name='Значення (колір)')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='shop.attribute', verbose_name='Атрибут')),
            ],
            options={
                'verbose_name': 'Значення атрибута',
                'verbose_name_plural': 'Значення атрибутів',
                'unique_together': {('attribute', 'value_text')},
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('slug', models.SlugField(blank=True, max_length=100, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('image', models.ImageField(blank=True, upload_to='categories/', verbose_name='Зображення')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('full_slug', models.CharField(blank=True, editable=False, max_length=500, unique=True, verbose_name='Повний URL-шлях')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='shop.category', verbose_name='Батьківська категорія')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='attribute',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Якщо не вибрано жодної, атрибут доступний для всіх категорій', related_name='attributes', to='shop.category', verbose_name='Категорії'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ПІБ')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Адреса доставки')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Місто')),
                ('nova_post_office', models.CharField(blank=True, max_length=50, verbose_name='Відділення Нової Пошти')),
                ('delivery_method', models.CharField(choices=[('nova_post', 'Нова Пошта'), ('ukr_post', 'Укрпошта'), ('courier', "Кур'єр"), ('pickup', 'Самовивіз')], default='nova_post', max_length=20, verbose_name='Спосіб доставки')),
                ('comment', models.TextField(blank=True, verbose_name='Коментар до замовлення')),
                ('products', models.JSONField(default=list, help_text='[{"id": 1, "name": "...", "price": 1000, "quantity": 2, "image": "...", "attributes": [...]}]', verbose_name='Товари')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сума замовлення')),
                ('status', models.CharField(choices=[('new', 'Нове'), ('processing', 'Обробляється'), ('paid', 'Оплачено'), ('shipped', 'Відправлено'), ('delivered', 'Доставлено'), ('cancelled', 'Скасовано')], default='new', max_length=20, verbose_name='Статус')),
                ('payment_id', models.CharField(blank=True, max_length=100, verbose_name='ID платежу')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='Спосіб оплати')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='shop_order_status_63c2c0_idx'), models.Index(fields=['is_paid'], name='shop_order_is_paid_462761_idx'), models.Index(fields=['created_at'], name='shop_order_created_86b012_idx')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='URL')),
                ('description', models.TextField(verbose_name='Опис')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, help_text='Заповніть, якщо товар зі знижкою', max_digits=10, null=True, verbose_name='Стара ціна')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Кількість на складі')),
                ('image', models.ImageField(blank=True, upload_to='products/', verbose_name='Головне зображення')),
                ('gallery_images', models.JSONField(blank=True, default=list, help_text='Список шляхів до додаткових зображень', verbose_name='Галерея зображень')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('is_new', models.BooleanField(default=False, verbose_name='Новинка')),
                ('is_bestseller', models.BooleanField(default=False, verbose_name='Хіт продажів')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='SEO заголовок')),
                ('meta_description', models.TextField(blank=True, max_length=500, verbose_name='SEO опис')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Додаткова ціна')),
                ('attribute_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.attributevalue', verbose_name='Значення атрибута')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Значення характеристики товару',
                'verbose_name_plural': 'Значення характеристик товарів',
                'unique_together': {('product', 'attribute_value')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='attribute_values',
            field=models.ManyToManyField(blank=True, related_name='products', through='shop.ProductAttributeValue', to='shop.attributevalue', verbose_name='Значення характеристик'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='shop_produc_slug_76971b_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_active'], name='shop_produc_categor_6c2d8c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_new'], name='shop_produc_is_new_008da4_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_bestseller'], name='shop_produc_is_best_ef4372_idx'),
        ),
    ]
