# Generated by Django 6.0.4 on 2026-04-14 22:33

import django.core.validators
import django.db.models.deletion
import mptt.fields
import shop.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Бренд')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/', verbose_name='Логотип')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренди',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True, verbose_name='Ключ сесії')),
                ('items', models.JSONField(default=list, verbose_name='Товари в кошику')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Кошик',
                'verbose_name_plural': 'Кошики',
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва акції')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('promotion_type', models.CharField(choices=[('new', 'Новинка'), ('bestseller', 'Хіт продажів'), ('sale', 'Розпродаж'), ('discount', 'Знижка'), ('seasonal', 'Сезонна'), ('black_friday', "Чорна п'ятниця"), ('recommended', 'Рекомендуємо')], max_length=20, verbose_name='Тип акції')),
                ('discount_percent', models.PositiveIntegerField(default=0, verbose_name='Відсоток знижки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('start_date', models.DateTimeField(verbose_name='Дата початку')),
                ('end_date', models.DateTimeField(verbose_name='Дата закінчення')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
            ],
            options={
                'verbose_name': 'Акція',
                'verbose_name_plural': 'Акції',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Категорія')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='URL')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Зображення')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='shop.category', verbose_name='Батьківська категорія')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ПІБ')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Адреса доставки')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Місто')),
                ('nova_post_office', models.CharField(blank=True, max_length=50, verbose_name='Відділення Нової Пошти')),
                ('delivery_method', models.CharField(choices=[('nova_post', 'Нова Пошта'), ('ukr_post', 'Укрпошта'), ('courier', "Кур'єр"), ('pickup', 'Самовивіз')], default='nova_post', max_length=20, verbose_name='Спосіб доставки')),
                ('comment', models.TextField(blank=True, verbose_name='Коментар до замовлення')),
                ('products', models.JSONField(default=list, help_text='[{"id": 1, "name": "...", "price": 1000, "quantity": 2}]', verbose_name='Товари')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сума замовлення')),
                ('status', models.CharField(choices=[('new', 'Нове'), ('processing', 'Обробляється'), ('paid', 'Оплачено'), ('shipped', 'Відправлено'), ('delivered', 'Доставлено'), ('cancelled', 'Скасовано')], default='new', max_length=20, verbose_name='Статус')),
                ('payment_id', models.CharField(blank=True, max_length=100, verbose_name='ID платежу')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='Спосіб оплати')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='shop_order_status_63c2c0_idx'), models.Index(fields=['is_paid'], name='shop_order_is_paid_462761_idx')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Назва')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True, verbose_name='URL')),
                ('article', models.CharField(blank=True, max_length=50, null=True, verbose_name='Артикул')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Код товару')),
                ('description', models.TextField(blank=True, verbose_name='Короткий опис')),
                ('full_description', models.TextField(blank=True, verbose_name='Повний опис')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ціна')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Стара ціна')),
                ('discount', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Знижка, %')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Кількість на складі')),
                ('available', models.BooleanField(default=True, verbose_name='Наявність')),
                ('warranty', models.PositiveIntegerField(default=0, verbose_name='Гарантія, місяців')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='Країна виробництва')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to=shop.models.get_image_upload_path, verbose_name='Головне зображення')),
                ('attributes', models.JSONField(blank=True, help_text='Додаткові характеристики у форматі JSON', null=True, verbose_name='Характеристики')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Рейтинг')),
                ('reviews_count', models.PositiveIntegerField(default=0, verbose_name='Кількість відгуків')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.brand', verbose_name='Бренд')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category', verbose_name='Категорія')),
                ('promotions', models.ManyToManyField(blank=True, related_name='products', to='shop.promotion', verbose_name='Акції')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=shop.models.get_image_upload_path, verbose_name='Зображення')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Альтернативний текст')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата додавання')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='shop.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Додаткове зображення',
                'verbose_name_plural': 'Додаткові зображення',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='properties', to='shop.category', verbose_name='Категорії')),
            ],
            options={
                'verbose_name': 'Властивість',
                'verbose_name_plural': 'Властивості',
            },
        ),
        migrations.CreateModel(
            name='PropertyValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Значення')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='shop.property', verbose_name='Властивість')),
            ],
            options={
                'verbose_name': 'Значення властивості',
                'verbose_name_plural': 'Значення властивостей',
                'unique_together': {('property', 'value')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='property_values',
            field=models.ManyToManyField(blank=True, related_name='products', to='shop.propertyvalue', verbose_name='Значення властивостей'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Оцінка')),
                ('comment', models.TextField(verbose_name='Коментар')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Опубліковано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='shop.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Відгук',
                'verbose_name_plural': 'Відгуки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('page', models.CharField(max_length=200)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='shop_produc_slug_76971b_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'available'], name='shop_produc_categor_322d96_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price'], name='shop_produc_price_3b79b5_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand'], name='shop_produc_brand_i_835a1f_idx'),
        ),
    ]
