# Generated by Django 6.0.4 on 2026-04-13 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Рейтинг'),
        ),
        migrations.AddField(
            model_name='product',
            name='reviews_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Кількість відгуків'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Оцінка')),
                ('comment', models.TextField(verbose_name='Коментар')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Опубліковано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='shop.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Відгук',
                'verbose_name_plural': 'Відгуки',
                'ordering': ['-created_at'],
            },
        ),
    ]
