# Generated by Django 6.0.4 on 2026-04-20 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='external_id',
            field=models.CharField(blank=True, help_text='ID з імпорту (наприклад, group_123, cat_456)', max_length=100, null=True, unique=True, verbose_name='Зовнішній ID'),
        ),
    ]
