# Generated by Django 6.0.4 on 2026-04-23 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_category_external_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentlyViewed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40, verbose_name='Ключ сесії')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата перегляду')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recently_viewed', to='shop.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Переглянутий товар',
                'verbose_name_plural': 'Історія переглядів',
                'ordering': ['-viewed_at'],
                'unique_together': {('session_key', 'product')},
            },
        ),
    ]
