# Generated by Django 6.0.4 on 2026-04-24 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_recentlyviewed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Назва')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True, verbose_name='URL')),
                ('service_type', models.CharField(choices=[('service', 'Послуга'), ('spare_part', 'Комплектуюча'), ('consumable', 'Витратний матеріал')], default='service', max_length=20, verbose_name='Тип')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ціна')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, help_text='Для аналітики', max_digits=12, null=True, verbose_name='Собівартість')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('execution_time', models.CharField(blank=True, help_text='Наприклад: 1-2 дня, 1 година', max_length=100, verbose_name='Час виконання')),
                ('specifications', models.JSONField(blank=True, default=dict, verbose_name='Характеристики')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Популярна послуга')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
            ],
            options={
                'verbose_name': 'Послуга/Комплектуюча',
                'verbose_name_plural': 'Послуги та комплектуючі',
                'ordering': ['service_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LegalEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Назва організації')),
                ('short_name', models.CharField(blank=True, max_length=100, verbose_name='Коротка назва')),
                ('code_edrpou', models.CharField(help_text='Унікальний код підприємства', max_length=10, unique=True, verbose_name='Код ЄДРПОУ')),
                ('tax_number', models.CharField(blank=True, help_text='Індивідуальний податковий номер', max_length=12, verbose_name='ІПН')),
                ('vat_number', models.CharField(blank=True, help_text='Свідоцтво ПДВ', max_length=12, verbose_name='Платник ПДВ')),
                ('legal_address', models.TextField(blank=True, verbose_name='Юридична адреса')),
                ('actual_address', models.TextField(blank=True, verbose_name='Фактична адреса')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Веб-сайт')),
                ('bank_name', models.CharField(blank=True, max_length=200, verbose_name='Назва банку')),
                ('bank_account', models.CharField(blank=True, max_length=29, verbose_name='Розрахунковий рахунок')),
                ('bank_mfo', models.CharField(blank=True, max_length=6, verbose_name='МФО')),
                ('director', models.CharField(blank=True, max_length=200, verbose_name='Директор/Керівник')),
                ('accountant', models.CharField(blank=True, max_length=200, verbose_name='Головний бухгалтер')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('notes', models.TextField(blank=True, verbose_name='Примітки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
            ],
            options={
                'verbose_name': 'Юридична особа',
                'verbose_name_plural': 'Юридичні особи',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code_edrpou'], name='shop_legale_code_ed_09a1cd_idx'), models.Index(fields=['is_active'], name='shop_legale_is_acti_db2f10_idx')],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='Номер рахунку')),
                ('invoice_date', models.DateField(auto_now_add=True, verbose_name='Дата виставлення')),
                ('seller', models.CharField(default='ТОВ "TechShop"', max_length=250, verbose_name='Продавець')),
                ('seller_code', models.CharField(default='12345678', max_length=10, verbose_name='Код ЄДРПОУ продавця')),
                ('seller_address', models.TextField(default='м. Київ, вул. Технічна, 1', verbose_name='Адреса продавця')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сума без ПДВ')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=20, max_digits=5, verbose_name='Ставка ПДВ')),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сума ПДВ')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Загальна сума')),
                ('payment_status', models.CharField(choices=[('unpaid', 'Не оплачений'), ('partial', 'Частково оплачений'), ('paid', 'Оплачений'), ('overdue', 'Прострочений')], default='unpaid', max_length=20, verbose_name='Статус оплати')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сплачено')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Дата оплати')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='Спосіб оплати')),
                ('notes', models.TextField(blank=True, verbose_name='Примітки')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Термін оплати')),
                ('created_by', models.CharField(blank=True, max_length=100, verbose_name='Створив')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.order', verbose_name='Замовлення')),
                ('legal_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='shop.legalentity', verbose_name='Отримувач (Покупець)')),
            ],
            options={
                'verbose_name': 'Рахунок-фактура',
                'verbose_name_plural': 'Рахунки-фактури',
                'ordering': ['-invoice_date', '-invoice_number'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Назва')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Кількість')),
                ('unit', models.CharField(default='шт', max_length=20, verbose_name='Одиниця виміру')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Ціна')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=20, max_digits=5, verbose_name='Ставка ПДВ')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сума')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.invoice', verbose_name='Рахунок')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Товар')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.service', verbose_name='Послуга/Товар')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Назва категорії')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('icon', models.CharField(blank=True, help_text='Наприклад: fa-print', max_length=50, verbose_name='Іконка (Font Awesome)')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок сортування')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.servicecategory', verbose_name='Батьківська категорія')),
            ],
            options={
                'verbose_name': 'Категорія послуг',
                'verbose_name_plural': 'Категорії послуг',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='shop.servicecategory', verbose_name='Категорія'),
        ),
    ]
