# Generated by Django 6.0.4 on 2026-04-24 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_service_legalentity_invoice_invoiceitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_required',
            field=models.BooleanField(default=False, verbose_name='Потрібен рахунок-фактура'),
        ),
        migrations.AddField(
            model_name='order',
            name='legal_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.legalentity', verbose_name='Юридична особа (покупець)'),
        ),
    ]
