# Generated by Django 6.0.4 on 2026-04-24 07:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order_invoice_required_order_legal_entity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата виставлення'),
        ),
    ]
